sudo:
  required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk11

before_install:
  - chmod +x mvnw

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

script:
  - ./mvnw clean install -B

after_success:
  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  #Docker Login
  - docker login -u $DOCKER_USER --password-stdin $DOCKER_PASS
  #IntellST-OpenCV
  - export intellst=lindvior2/intellst-opencv
  - docker build -t $intellst:$COMMIT ./
  - docker tag $intellst:$COMMIT $intellst:$TAG
  - docker push $intellst
