sudo:
  required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk11

before_install:
  - chmod +x mvnw

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

after_success:
  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  #Docker Login
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  #IntellST-OpenCV
  - export IntellST-OpenCV=lindvior2/intellst-opencv
  - docker build -t $IntellST-OpenCV:$COMMIT ./
  - docker tag $IntellST-OpenCV:$COMMIT $IntellST-OpenCV:$TAG
  - docker push $IntellST-OpenCV
script:
  - ./mvnw clean install -B