sudo:
  required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk11

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

after_success:

  #LOGIN
  - docker login -u $D_USER -p $D_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  #IntellST-OpenCV
  - export IntellST_OpenCV=mDKoBrA/IntellST-OpenCV
  - docker build -t $IntellST_OpenCV:$COMMIT ./
  - docker tag $IntellST_OpenCV:$COMMIT $IntellST_OpenCV:$TAG
  - docker push $IntellST_OpenCV

